apiVersion: apps/v1
kind: Deployment
metadata:
  name: sjdufh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sjdufh
  template:
    metadata:
      labels:
        app: sjdufh
    spec:
      containers:
      - image: okteto.dev/sjdufh:latest
        name: sjdufh
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "8e9108a2-786c-4272-9741-0a3e51914c69"
        - name: Vless_Path
          value: "/vh23f8475"
        - name: Vmess_UUID
          value: "8e9108a2-786c-4272-9741-0a3e51914c69"
        - name: Vmess_Path
          value: "/vmueyd8456"
        - name: Share_Path
          value: "/v2link"
